### ISSUE TITLE
Weapons turning in shulker boxes

### ISSUE THREAD

**Issue by TheSast** [ICY105/CombatPlus#1]
Whenever I hold an item from this data pack they will transform into green shulker boxes containing the item as soon as I try to use it it transforms into another shulkerbox, this happens with every cmbat+ item except arc stars and knives but if I melee something with the knife it transforms into the shulkerbox.

**Comment by ICY105** [comment]
Can you answer these debug questions:

1. What datapack(s) do you have installed (including ones made by me- include version if possible).

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.

**Comment by TheSast** [comment]
> What datapack(s) do you have installed (including ones made by me- include version if possible).

Creatures+ v0.2
CaveBiomes v1.0.1
Combat+ v1.0.1
DatapackUtilities v2.0.2a
DimensionalRift v2.2.0
1.14 fossils to dungeon datapack (only one version)
1.14 outpost structures datapack (only one version)
Kyu and Q's SUHC (only one version)

> Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded ]).

```
Reloaded!
*SUHC datapack introduction text*
[Loaded Datapack Utils v2.0.2a]
*2nd SUHC datapack introduction text*
[Loaded Combat+ v1.0.1]

[Loaded Cave Biomes v1.0.1]
*3rd SUHC datapack introduction text*
```

> What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.

Minecraft 1.14.4 (1.14.4-OptiFine_HD_U_F4/vanilla)
I tried running it on my private server too the issue is exactly the same.
Minecraft 1.14.4 PaperSpigot version git-Paper-226
